name: etsam
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.14=py313h46c70d0_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.3.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgomp=15.1.0=h767d61c_2
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.1=hee588c1_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.0=h7b32b05_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1.1=pyh145f28c_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py313h536fd9c_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - python=3.13.3=hf636f53_101_cp313
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.13=7_cp313
  - pyzmq=26.4.0=py313h8e95178_0
  - readline=8.2=h8c095d6_2
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_hd72426e_102
  - tornado=6.5.1=py313h536fd9c_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.0=pyhe01879c_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - pip:
      - absl-py==2.3.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.12
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - anytree==2.13.0
      - attrs==25.3.0
      - backoff==2.2.1
      - black==25.1.0
      - boto3==1.38.34
      - botocore==1.38.34
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cloudpickle==3.1.1
      - contourpy==1.3.3
      - cryoet-data-portal==4.4.1
      - cycler==0.12.1
      - deepmerge==2.0
      - dnspython==2.8.0
      - docstring-parser==0.16
      - dotted-dict==1.1.3
      - dvuploader==0.3.0
      - easydataverse==0.4.4
      - einops==0.8.1
      - email-validator==2.3.0
      - empatches==0.2.3
      - filelock==3.18.0
      - fonttools==4.61.1
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gql==3.5.3
      - graphql-core==3.2.6
      - grpcio==1.73.0
      - h11==0.16.0
      - hf-xet==1.1.3
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.33.0
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - iopath==0.1.10
      - jinja2==3.1.6
      - jmespath==1.0.1
      - jsonargparse==4.40.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - libcst==1.8.1
      - lightning==2.5.1.post0
      - lightning-utilities==0.14.3
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - monai==1.4.0
      - moreorless==0.5.0
      - mpmath==1.3.0
      - mrcfile==1.5.4
      - multidict==6.4.4
      - mypy-extensions==1.1.0
      - narwhals==2.16.0
      - ndjson==0.3.1
      - networkx==3.5
      - nob==0.8.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==13.590.48
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pandas==2.3.0
      - pathspec==0.12.1
      - pillow==11.2.1
      - plotly==6.5.2
      - portalocker==3.1.1
      - propcache==0.3.2
      - protobuf==4.24.4
      - pyaml==24.12.1
      - pycocotools==2.0.10
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pydataverse==0.3.5
      - pyparsing==3.3.2
      - python-dotenv==1.1.0
      - python-forge==18.6.0
      - pytorch-lightning==2.5.1.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyyaml-ft==8.0.0
      - referencing==0.37.0
      - requests==2.32.4
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rpds-py==0.29.0
      - s3transfer==0.13.0
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentry-sdk==2.29.1
      - setproctitle==1.3.6
      - setuptools==80.9.0
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - standard-imghdr==3.13.0
      - stdlibs==2025.5.10
      - strcase==1.0.0
      - submitit==1.5.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==8.5.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensordict==0.8.3
      - termcolor==3.1.0
      - tifffile==2025.6.1
      - timm==1.0.15
      - toml==0.10.2
      - tomlkit==0.13.3
      - torch==2.7.1
      - torcheval==0.0.7
      - torchmetrics==1.7.2
      - torchvision==0.22.1
      - tqdm==4.67.1
      - trailrunner==1.4.0
      - triton==3.3.1
      - typer==0.15.4
      - typeshed-client==2.7.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - ufmt==2.8.0
      - urllib3==2.4.0
      - usort==1.0.8.post1
      - wandb==0.20.1
      - werkzeug==3.1.3
      - xmltodict==0.13.0
      - yacs==0.1.8
      - yarl==1.20.1
